name: Build Windows

on:
  push:
    paths:
      - "**/workflows/build_windows.yml"
      - "**/Source/**"
      - "**/Tests/**"
      - "**/ThirdParty/**"
      - "**/CMakeLists.txt"
      - "**/.gitmodules"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  BUILD_TYPE: Release

jobs:
  luau:
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build Luau
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE --parallel 4 --target LuaBridgeTestsLuau

    - name: Test Luau
      working-directory: ${{runner.workspace}}/build/Tests/Release
      shell: bash
      run: ./LuaBridgeTestsLuau.exe